version: "3"

services:
  cljs:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
      - ~/.lein:/root/.lein
    ports:
      - "9500:9500"
      - "6666:6666"
